Create Interstellar-Network.md
Interstellar-Network/Grants-Program pull request #1
Opened 2021-11-03 16:34 UTC by nashjl

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [ ] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

2021-11-23 16:52 UTC, nathanprat requested changes

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +> See the [Grants Program Process](https://github.com/w3f/Grants-Program/#pencil-process) on how to submit a proposal.
A supprimer

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +If this application is in response to an RFP, please indicate this on the first line of this section.
TODO

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +If this is an application for a follow-up grant (the continuation of an earlier, successful W3F grant), please provide name and/or pull request of said grant on the first line of this section.
A supprimer

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- An indication of why your team is interested in creating this project.
TODO

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +We think that Hardware security, Trusted Execution Environnement TEE and especially Trusted User Interface TUI can provide a level of hardware security comparable to hardware wallet. Mobile UI securi
"a level of hardware security comparable to hardware wallet" -> "a level of security comparable to hardware wallet" ?

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +We think that Hardware security, Trusted Execution Environnement TEE and especially Trusted User Interface TUI can provide a level of hardware security comparable to hardware wallet. Mobile UI securi
"They can easily build fake UI that mislead user to trigger tampered transaction." -> "They can easily build fake UIs that mislead users to trigger a tampered transaction." ou plutot tout au singulier?

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +Interstellar is a novel type of non-custodial **frictionless** decentralized wallet with **hardware security level**, designed to support blockchain and DeFi **mass market adoption**.
"hardware security level" -> "hardware-level security" ?

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +The project phase 1 focus on two of the core components of the Interstaller solution: An OCW garbled circuit factory GCF (to manage an external Garbled Circuit Genrator service) and an implementation
typos

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Every schemes  based on Garbled Circuit generator and evaluator
ça veut dire quoi?

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +The project phase 1 focus on two of the core components of the Interstaller solution: An OCW garbled circuit factory GCF (to manage an external Garbled Circuit Genrator service) and an implementation
"We designed this Garbled circuit Factory to be used by substrate devellopers regardless of Interstellar solution." attention, il vaut peut etre mieux eviter de trop s'engager?

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Post Quantum encryption and signature scheme implementation (NIST candiate examples)
tous les points : plutôt mettre ça dans un "future plans"? Ou quelque chose ce genre?

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +### Project Details
TODO

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +```
supprimer le full path

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +![images8](https://user-images.githubusercontent.com/4605611/141358949-5c0eaffb-e0c3-437d-88f9-7ab948f782a0.png)
ajouter un screenshot new(=segments) vs old(=white noise), avec sreenshot unique vs plusieurs combinés pour montrer la lisibilité

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +We expect the teams to already have a solid idea about your project's expected final state. Therefore, we ask the teams to submit (where relevant)
a supprimer

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +Behavioral Biometric: each user has a unique typing pattern for a sequence of digits on a keypad. So, if a bad actor tries to replicate this pattern. It will be detected with a 98% success rate. This
Plutôt dans "future plans"?

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +***Link to Intertsellar Light paper**
idem, plutot dans "future plans"?

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +Help us locate your project in the Polkadot/Substrate/Kusama landscape and what problems it tries to solve by answering each of these questions:
a supprimer

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +We designed our Transaction Validation protocol to benfit to other wallet or Dapp. We think it could also be complemetary down the road to mobile light client like substrate connect (check future pla
typos

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Are there any other projects similar to yours in the Substrate / Polkadot / Kusama ecosystem?
formatting

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Jean-Louis Honenen
typo

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +### Contact
TODO

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +Please describe the team's relevant experience. If your project involves development work, we would appreciate it if you singled out a few interesting projects or contributions made by team members i
a supprimer

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +If anyone on your team has applied for a grant at the Web3 Foundation previously, please list the name of the project and legal entity here.
a supprimer

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +### Team Code Repos
TODO

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +### Team LinkedIn Profiles (if available)
formatting

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +
TODO

2021-11-23 16:52 UTC, nathanprat commented on applications/Interstellar-Network.md
> +
formatting

2021-12-07 14:11 UTC, n-prat requested changes

2021-12-07 14:11 UTC, n-prat commented on applications/Interstellar-Network.md
> +- **Cross chain Swap feature** - based on a Continious Liquitity Pool (CLP like ThorChain but with higher security and performance) - leverages TEE/MPC/TTS + Trusted Transaction Validation protocol w
spelling: 
Continious Liquitity Pool -> Continuous Liquidity
liquitity -> liquidity
mutisig -> multisig

2021-12-07 14:11 UTC, n-prat commented on applications/Interstellar-Network.md
> +- A substrate Off-Chain Worker OCW Garbled Circuit Factory GCF to manage an external garbled circuit generator service (designed to be used by substrate devellopers regardless of Interstellar solutio
spelling:
devellopers -> developers

2021-12-07 14:11 UTC, n-prat commented on applications/Interstellar-Network.md
> +We want to target in priority Dapp providers in the DeFi ecosystem with develloper tools to integrate our solution with their Dapps. We think that our value proposition should be attractive to them.
spelling:
develloper -> developer

2021-12-07 14:11 UTC, n-prat commented on applications/Interstellar-Network.md
> +- **Features to securely send coins with social network messages (even to person with no-wallet)** - [Can an easy to set-up wallet be an efficient customer aquisition tool for DeFi players?](https://
spelling:
aquisition -> acquisition

2021-12-07 14:11 UTC, n-prat commented on applications/Interstellar-Network.md
> +- **User experience**  [Can an easy to set-up wallet be an efficient customer aquisition tool for DeFi players?](https://medium.com/@jlleleu/can-be-an-easy-to-set-up-wallet-an-efficient-customer-acqu
spelling:
aquisition -> acquisition

2021-12-07 14:11 UTC, n-prat commented on applications/Interstellar-Network.md
> +The **Interstellar - Wallet Phase 1** W3F Grant Proposal focuses on two of the core components of the Interstaller solution:
spelling:
Interstaller -> Interstellar

2021-12-07 14:11 UTC, n-prat commented on applications/Interstellar-Network.md
> +- Post Quantum encryption and signature scheme implementation (NIST candiate examples)
spelling:
candiate -> candidate

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +#### Garbled Circuit Factory **previous vork**
spelling:
vork -> work

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +The team has already develloped a strong authentication solution with circuits based on JustGarble implememtation https://cseweb.ucsd.edu/groups/justgarble/ that we customized with Free XOR and Half
spelling:
develloped -> developed
implememtation -> implementation

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +We achieved a production ready platform with significant performance on the logic circuit and garbled circuit production with AES-NI. The whole pipeline use optimized memory mangement and avoid seria
spelling:
mangement -> management

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +We designed our validation transaction protocol to benfit to other wallets or Dapps. We think it could also be complemetary down the road to mobile light client like substrate connect (check **Future
spelling:
benfit -> benefit
complemetary -> complementary

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Improvement of our Visual Cryptography scheme by reintroducing pure visual cryptography frame to display character, figures, images. It should increase the complexity, cost and ressources required
spelling:
ressources -> resources

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +1 pratn@DESKTOP-U6PJB3U:~/workspace/j2l/lib_server/build$ ./circuit_display_gen_bench -nb_circuits_to_generate=5000
supprimer `pratn@DESKTOP-U6PJB3U:~/workspace/j2l/lib_server/build$`

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +| 0b. | Documentation | We will provide both **inline documentation** of the code and a basic **tutorial** that explains how a user can create and set-up a VHDL Master File, lauch Garbled Circuit gen
spelling:
lauch -> launch

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +| 3. | Substrate GCF CFG CLI| a CLI to set-up  GCF configuration palllet |
spelling:
palllet -> pallet

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +| 0b. | Documentation | We will provide both **inline documentation** of the code and a basic **tutorial** that explains how a user can manage Garbled circuit cid in pallets. with a transaction valid
spelling:
environement -> environment

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +| 1. | substrate modules Authenicator port in TEE | We will migrate Authenticator in substraTEE/IntegriTEE workers |
spelling:
Authenicator -> Authenticator

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- We aim at develloping a user comunity and get in talks with Dapp and especially DeFi players with a taylored value proposition for them.
spelling:
develloping -> developing
comunity -> community
taylored -> tailored

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Math Wallet is based on MPC that requires heavier computation ressources. They also envision smartcards with screen for users. It's comparable to our level of security, but more expensive, cumberso
spelling:
ressources -> resources

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Add behavioral biometric feature
spelling:
behavioral -> behavioural

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Include a TEE layer 2 to manage a Root of trust based on full HSM hardware ( with YubiHSM typeof solution) to provide a 3 tier distributed HSM capability.
typo:
typeof -> type of

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Research on other human brain decryption capabilities (like Visual Cryptography, audio cryptography, etc..): the long term Goal is to increase our capabilities to descriminate real humans from bots
spelling:
descriminate -> discriminate

2021-12-07 14:11 UTC, nathanprat commented on applications/Interstellar-Network.md
> +- Wheter there are any other teams who have already contributed (financially) to the project.
spelling:
Wheter -> Whether

2021-12-08 16:48 UTC, merged